# リリースをnpm publishするworkflow
name: Publish to npm

on:
  release:
    types: 
      - published 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: dump context
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - name: get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: bump version
        run: |
          npm --no-git-tag-version version ${{ steps.get_version.outputs.VERSION }}
      - name: publish
        # npm ci & npm run build & npm publish
        run: |
          cat package.json
          cat package-lock.json
      - name: Commit updates
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: "Bump version: ${{ steps.get_version.outputs.VERSION }}"
          add: "['package.json', 'package-lock.json']"
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - name: To slack mrkdwn
        id: set-body
        uses: actions/github-script@v6
        with:
          script: return require('slackify-markdown')(${{ toJSON(github.event.release.body) }})
          result-encoding: json
          debug: true
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "note": ${{ steps.set-body.outputs.result }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
